Description: "My first tamplate for Cloud Formation"

Resources:
  mytestCloudFormationVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: "true"
      Tags:
      - Key: name
        Value: firstDeployment